### ISSUE TITLE
安定版には 4.0 を加える

### ISSUE THREAD

**Issue by ran-huang** [you06/tidb-docs-jp#5]
よろしければ、PRを作成させていただけませんか。
日本語に興味があるし、TiDBもちょっと分かる。

**Comment by you06** [comment]
PR 作成へようこそ！
人手不足のため、重要なコンテンツを翻訳は優先するが良い。

- 高レベルのアーキテクチャ
- 実践ガイド
- `TiDB`ツールガイド

他のチャプターはも歓迎します～

**Comment by ran-huang** [comment]
PRを一つ作成した〜
他のチャプターを翻訳したいだけど、今はちょっと都合が悪いです。今度必ずもっとドキュメントを翻訳してみます。
